apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: planespotter

resources:
  - ../namespace.yaml
  # Database
  - ../database/configmap.yaml
  - ../database/secret.yaml
  - ../database/pvc.yaml
  - ../database/deployment.yaml
  - ../database/service.yaml
  # Cache
  - ../cache/deployment.yaml
  - ../cache/service.yaml
  # API Server
  - ../api-server/configmap.yaml
  - ../api-server/secret.yaml
  - ../api-server/deployment.yaml
  - ../api-server/service.yaml
  # Frontend
  - ../frontend/configmap.yaml
  - ../frontend/deployment.yaml
  - ../frontend/service.yaml
  - ../frontend/ingress.yaml
  # ADSB Sync
  - ../adsb-sync/configmap.yaml
  - ../adsb-sync/deployment.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: planespotter
